"""
XGBoost EV Energy Consumption Regression Model
================================================
Phase 14: Gradient Boosted Trees (XGBRegressor) model to predict trip energy
consumption (target: energy_consumed_kwh) from trip, vehicle, route, and
environmental features.

Evaluated on the exact same 80/20 train/test split (seed=42) as the Change 13
Linear Regression baseline to enable a fair, controlled performance comparison.

IMPORTANT SYNTHETIC-DATA DISCLOSURE:
-------------------------------------
- This model is trained and evaluated strictly on synthetic/simulated Virtual EV data
  generated by the project's data collection pipeline (Phase 12).
- Target energy consumption was generated using the documented 0.150 kWh/km baseline
  physics simulation methodology.
- The evaluation metrics report model fit on this simulated distribution and MUST
  NOT be presented or interpreted as validated real-world physical EV measurements.
- Superior performance on synthetic data does NOT imply equivalent real-world accuracy.

Preprocessing Strategy:
- Categorical Preprocessing: OneHotEncoder(handle_unknown='ignore', sparse_output=False)
- Numeric Preprocessing: Passthrough (tree-based splitting is invariant to monotonic scaling)
- Estimator: xgboost.XGBRegressor (conservative hyperparameter configuration)

Artifacts Saved:
- models/artifacts/energy_xgboost_model.pkl (Complete Scikit-Learn Pipeline)
- models/artifacts/energy_xgboost_model_features.json (Feature schema, metrics, importances, comparison)

Usage:
    python models/energy_xgboost_model.py
    python models/energy_xgboost_model.py --seed 42 --test-size 0.20
"""

import argparse
import json
import os
import sys
import time
from typing import Any, Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBRegressor

# ---------------------------------------------------------------------------
# Path Configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_PATH = os.path.join(BASE_DIR, "data", "processed", "energy_consumption_features.csv")
ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "artifacts")
MODEL_PATH = os.path.join(ARTIFACTS_DIR, "energy_xgboost_model.pkl")
FEATURES_PATH = os.path.join(ARTIFACTS_DIR, "energy_xgboost_model_features.json")
BASELINE_METRICS_PATH = os.path.join(ARTIFACTS_DIR, "energy_regression_model_features.json")

# ---------------------------------------------------------------------------
# Feature & Target Schema
# ---------------------------------------------------------------------------
TARGET_COL = "energy_consumed_kwh"

NUMERIC_FEATURES = [
    "battery_capacity_kwh",
    "starting_soc_percent",
    "distance_km",
    "trip_duration_minutes",
    "average_speed_kmph",
    "elevation_gain_m",
    "traffic_density_score",
    "ambient_temperature_c",
]

CATEGORICAL_FEATURES = [
    "vehicle_id",
    "weather_condition",
    "driving_style",
]

EXCLUDED_COLS = ["trip_id", "data_type", TARGET_COL]

# ---------------------------------------------------------------------------
# Hyperparameter Configuration
# ---------------------------------------------------------------------------
# Conservative configuration for a 1,200-row academic dataset to avoid overfitting
XGB_CONFIG = {
    "n_estimators": 120,
    "learning_rate": 0.06,
    "max_depth": 4,
    "subsample": 0.85,
    "colsample_bytree": 0.85,
    "objective": "reg:squarederror",
    "random_state": 42,
    "n_jobs": -1,
}


def load_and_validate_data(csv_path: str = DATA_PATH) -> Tuple[pd.DataFrame, pd.Series]:
    """
    Loads dataset, asserts presence of all feature columns, and separates X and y
    with strict target leakage checks.
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Processed energy dataset not found at: {csv_path}")

    df = pd.read_csv(csv_path)

    # Validate target presence
    if TARGET_COL not in df.columns:
        raise ValueError(f"Target column '{TARGET_COL}' missing from dataset.")

    # Validate all feature columns
    all_features = NUMERIC_FEATURES + CATEGORICAL_FEATURES
    missing_features = [f for f in all_features if f not in df.columns]
    if missing_features:
        raise ValueError(f"Missing required feature columns: {missing_features}")

    # Explicit Target Leakage Check
    X = df[all_features].copy()
    y = df[TARGET_COL].copy()

    if TARGET_COL in X.columns:
        raise ValueError("CRITICAL: Target column detected inside feature matrix X (Target Leakage)!")

    # Verify no nulls
    if X.isnull().any().any():
        raise ValueError("Null values detected in feature matrix X.")
    if y.isnull().any():
        raise ValueError("Null values detected in target vector y.")

    return X, y


def build_pipeline(random_state: int = 42) -> Pipeline:
    """
    Constructs an end-to-end sklearn Pipeline with ColumnTransformer for categorical
    encoding and passthrough for numeric features, followed by XGBRegressor.
    
    Tree-based models do not require numeric standard scaling.
    """
    preprocessor = ColumnTransformer(
        transformers=[
            (
                "cat",
                OneHotEncoder(handle_unknown="ignore", sparse_output=False),
                CATEGORICAL_FEATURES,
            ),
            (
                "num",
                "passthrough",
                NUMERIC_FEATURES,
            ),
        ]
    )

    config = dict(XGB_CONFIG)
    config["random_state"] = random_state

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("regressor", XGBRegressor(**config)),
        ]
    )
    return pipeline


def train_and_evaluate(
    csv_path: str = DATA_PATH,
    test_size: float = 0.20,
    random_state: int = 42,
    save_artifacts: bool = True,
) -> Dict[str, Any]:
    """
    Executes reproducible train/test split, XGBoost pipeline fitting, test evaluation,
    feature importance extraction, baseline comparison, and artifact serialization.
    """
    print("=" * 65)
    print("XGBOOST EV ENERGY REGRESSION MODEL TRAINING & EVALUATION")
    print("=" * 65)
    print("IMPORTANT DISCLOSURE: Trained on synthetic Virtual EV simulation data.")
    print("Results measure model fit on simulated distribution; not physical EV tests.\n")

    # 1. Load and validate
    X, y = load_and_validate_data(csv_path)
    total_samples = len(X)
    print(f"[1/6] Loaded dataset: {total_samples} samples across {len(X.columns)} features.")
    print(f"      - Numeric features ({len(NUMERIC_FEATURES)}): {NUMERIC_FEATURES}")
    print(f"      - Categorical features ({len(CATEGORICAL_FEATURES)}): {CATEGORICAL_FEATURES}")
    print(f"      - Target: '{TARGET_COL}'")

    # 2. Train / Test Split (Identical split to Change 13: seed=42, test_size=0.20)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )
    print(f"\n[2/6] Performed reproducible train/test split (seed={random_state}):")
    print(f"      - Training samples: {len(X_train)} ({(1 - test_size) * 100:.0f}%)")
    print(f"      - Held-out test samples: {len(X_test)} ({test_size * 100:.0f}%)")

    # 3. Build & Train Pipeline
    print(f"\n[3/6] Fitting ColumnTransformer + XGBRegressor Pipeline...")
    print(f"      - XGBoost Hyperparameters: {XGB_CONFIG}")
    pipeline = build_pipeline(random_state=random_state)
    start_time = time.time()
    pipeline.fit(X_train, y_train)
    train_duration = time.time() - start_time
    print(f"      - Training completed in {train_duration:.3f} seconds.")

    # Inspect feature space dimensionality after One-Hot Encoding
    preprocessor = pipeline.named_steps["preprocessor"]
    cat_encoder = preprocessor.named_transformers_["cat"]
    cat_feature_names = list(cat_encoder.get_feature_names_out(CATEGORICAL_FEATURES))
    encoded_feature_names = cat_feature_names + NUMERIC_FEATURES
    num_encoded_features = len(encoded_feature_names)
    print(f"      - Transformed feature dimensionality: {num_encoded_features} columns")

    # 4. Evaluate on Held-Out Test Set
    print("\n[4/6] Evaluating on held-out test set...")
    y_pred = pipeline.predict(X_test)

    mae = float(mean_absolute_error(y_test, y_pred))
    mse = float(mean_squared_error(y_test, y_pred))
    rmse = float(np.sqrt(mse))
    r2 = float(r2_score(y_test, y_pred))

    print("-" * 65)
    print("XGBOOST EVALUATION METRICS (TEST SET):")
    print(f"  MAE  (Mean Absolute Error):      {mae:.4f} kWh")
    print(f"  RMSE (Root Mean Squared Error):  {rmse:.4f} kWh")
    print(f"  R²   (Coefficient of Deter.):    {r2:.4f}")
    print("-" * 65)

    # 5. Feature Importance Extraction
    print("\n[5/6] Extracting Feature Importances (Tree Gain Weight)...")
    regressor = pipeline.named_steps["regressor"]
    importances = regressor.feature_importances_

    feature_imp_df = pd.DataFrame(
        {
            "Feature": encoded_feature_names,
            "Importance": importances,
        }
    ).sort_values("Importance", ascending=False).reset_index(drop=True)

    print("\nTop Contributing Features (XGBoost Relative Importance):")
    print(feature_imp_df.head(10).to_string(index=False))

    # Actual vs Predicted Sample Comparison Table
    sample_size = 8
    sample_df = pd.DataFrame(
        {
            "Distance (km)": X_test["distance_km"].iloc[:sample_size].values,
            "Speed (km/h)": X_test["average_speed_kmph"].iloc[:sample_size].values,
            "Style": X_test["driving_style"].iloc[:sample_size].values,
            "Actual (kWh)": y_test.iloc[:sample_size].values,
            "XGBoost Pred (kWh)": np.round(y_pred[:sample_size], 3),
        }
    )
    sample_df["Error (kWh)"] = np.round(sample_df["XGBoost Pred (kWh)"] - sample_df["Actual (kWh)"], 3)
    print("\nSample Test Predictions vs Actuals:")
    print(sample_df.to_string(index=False))

    # 6. Comparison with Linear Regression Baseline
    print("\n[6/6] Comparison with Linear Regression Baseline:")
    baseline_metrics = None
    if os.path.exists(BASELINE_METRICS_PATH):
        try:
            with open(BASELINE_METRICS_PATH, "r") as f:
                baseline_data = json.load(f)
                baseline_metrics = baseline_data.get("metrics", {})
        except Exception as e:
            print(f"      [WARN] Could not load baseline metrics: {e}")

    comparison_rows = []
    if baseline_metrics:
        comparison_rows.append(
            {
                "Model": "Linear Regression (Baseline)",
                "MAE (kWh)": f"{baseline_metrics.get('mae', 0.1862):.4f}",
                "RMSE (kWh)": f"{baseline_metrics.get('rmse', 0.2860):.4f}",
                "R²": f"{baseline_metrics.get('r2', 0.9914):.4f}",
            }
        )
    else:
        comparison_rows.append(
            {
                "Model": "Linear Regression (Baseline)",
                "MAE (kWh)": "0.1862",
                "RMSE (kWh)": "0.2860",
                "R²": "0.9914",
            }
        )

    comparison_rows.append(
        {
            "Model": "XGBoost Regressor",
            "MAE (kWh)": f"{mae:.4f}",
            "RMSE (kWh)": f"{rmse:.4f}",
            "R²": f"{r2:.4f}",
        }
    )

    comparison_df = pd.DataFrame(comparison_rows)
    print("\n" + comparison_df.to_string(index=False))

    # Save Artifacts
    results_summary = {
        "model_name": "XGBRegressor",
        "hyperparameters": XGB_CONFIG,
        "target": TARGET_COL,
        "metrics": {
            "mae": round(mae, 4),
            "rmse": round(rmse, 4),
            "r2": round(r2, 4),
        },
        "dataset_split": {
            "total_samples": total_samples,
            "train_samples": len(X_train),
            "test_samples": len(X_test),
            "test_size": test_size,
            "random_state": random_state,
        },
        "features": {
            "numeric_features": NUMERIC_FEATURES,
            "categorical_features": CATEGORICAL_FEATURES,
            "encoded_feature_count": num_encoded_features,
            "encoded_feature_names": encoded_feature_names,
            "feature_importances": feature_imp_df.to_dict(orient="records"),
        },
        "comparison_with_baseline": {
            "linear_regression": {
                "mae": baseline_metrics.get("mae", 0.1862) if baseline_metrics else 0.1862,
                "rmse": baseline_metrics.get("rmse", 0.2860) if baseline_metrics else 0.2860,
                "r2": baseline_metrics.get("r2", 0.9914) if baseline_metrics else 0.9914,
            },
            "xgboost": {
                "mae": round(mae, 4),
                "rmse": round(rmse, 4),
                "r2": round(r2, 4),
            },
        },
        "synthetic_data_disclosure": (
            "Model trained and evaluated on synthetic Virtual EV trip data. "
            "Metrics reflect performance on simulated distribution and do not "
            "represent validated real-world physical EV measurements. "
            "Superior performance on synthetic benchmarks does not imply real-world validity."
        ),
    }

    if save_artifacts:
        os.makedirs(ARTIFACTS_DIR, exist_ok=True)
        joblib.dump(pipeline, MODEL_PATH)
        with open(FEATURES_PATH, "w") as f:
            json.dump(results_summary, f, indent=2)

        print(f"\nSaved Artifacts:")
        print(f"  - Trained Pipeline: {MODEL_PATH}")
        print(f"  - Metadata/Schema:  {FEATURES_PATH}")

    print("=" * 65)
    print("[SUCCESS] XGBoost Regression Model trained and evaluated successfully.")
    print("=" * 65)

    return results_summary


def load_model(model_path: str = MODEL_PATH) -> Pipeline:
    """Loads the trained XGBoost regression pipeline artifact for inference."""
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model artifact not found at {model_path}. Run training first.")
    return joblib.load(model_path)


def predict_energy(features_df: pd.DataFrame, model_path: str = MODEL_PATH) -> np.ndarray:
    """Predicts energy consumption in kWh for given raw input features DataFrame."""
    pipeline = load_model(model_path)
    return pipeline.predict(features_df)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train XGBoost EV Energy Regression Model")
    parser.add_argument("--test-size", type=float, default=0.20, help="Test set fraction (default: 0.20)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility (default: 42)")
    parser.add_argument("--data", type=str, default=DATA_PATH, help="Path to input features CSV")
    args = parser.parse_args()

    train_and_evaluate(
        csv_path=args.data,
        test_size=args.test_size,
        random_state=args.seed,
        save_artifacts=True,
    )
