"""
Baseline EV Energy Consumption Regression Model
================================================
Phase 13: Baseline Linear Regression model to predict trip energy consumption
(target: energy_consumed_kwh) from trip, vehicle, route, and environmental features.

IMPORTANT SYNTHETIC-DATA DISCLOSURE:
-------------------------------------
- This model is trained and evaluated strictly on synthetic/simulated Virtual EV data
  generated by the project's data collection pipeline (Phase 12).
- Target energy consumption was generated using the documented 0.150 kWh/km baseline
  physics simulation methodology.
- The evaluation metrics report the model's goodness-of-fit on this simulated
  distribution and MUST NOT be presented or interpreted as validated real-world
  physical EV measurements.

Pipeline Components:
- Numeric Preprocessing: StandardScaler
- Categorical Preprocessing: OneHotEncoder(handle_unknown='ignore')
- Estimator: sklearn.linear_model.LinearRegression

Artifacts Saved:
- models/artifacts/energy_regression_model.pkl (Complete Scikit-Learn Pipeline)
- models/artifacts/energy_regression_model_features.json (Feature schema & metrics)

Usage:
    python models/energy_regression_model.py
    python models/energy_regression_model.py --seed 42 --test-size 0.20
"""

import argparse
import json
import os
import sys
from typing import Any, Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# ---------------------------------------------------------------------------
# Path Configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_PATH = os.path.join(BASE_DIR, "data", "processed", "energy_consumption_features.csv")
ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "artifacts")
MODEL_PATH = os.path.join(ARTIFACTS_DIR, "energy_regression_model.pkl")
FEATURES_PATH = os.path.join(ARTIFACTS_DIR, "energy_regression_model_features.json")

# ---------------------------------------------------------------------------
# Feature & Target Schema
# ---------------------------------------------------------------------------
TARGET_COL = "energy_consumed_kwh"

NUMERIC_FEATURES = [
    "battery_capacity_kwh",
    "starting_soc_percent",
    "distance_km",
    "trip_duration_minutes",
    "average_speed_kmph",
    "elevation_gain_m",
    "traffic_density_score",
    "ambient_temperature_c",
]

CATEGORICAL_FEATURES = [
    "vehicle_id",
    "weather_condition",
    "driving_style",
]

EXCLUDED_COLS = ["trip_id", "data_type", TARGET_COL]


def load_and_validate_data(csv_path: str = DATA_PATH) -> Tuple[pd.DataFrame, pd.Series]:
    """
    Loads dataset, asserts presence of all feature columns, and separates X and y
    with strict target leakage checks.
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Processed energy dataset not found at: {csv_path}")

    df = pd.read_csv(csv_path)

    # Validate target presence
    if TARGET_COL not in df.columns:
        raise ValueError(f"Target column '{TARGET_COL}' missing from dataset.")

    # Validate all feature columns
    all_features = NUMERIC_FEATURES + CATEGORICAL_FEATURES
    missing_features = [f for f in all_features if f not in df.columns]
    if missing_features:
        raise ValueError(f"Missing required feature columns: {missing_features}")

    # Explicit Target Leakage Check
    X = df[all_features].copy()
    y = df[TARGET_COL].copy()

    if TARGET_COL in X.columns:
        raise ValueError("CRITICAL: Target column detected inside feature matrix X (Target Leakage)!")

    # Verify no nulls
    if X.isnull().any().any():
        raise ValueError("Null values detected in feature matrix X.")
    if y.isnull().any():
        raise ValueError("Null values detected in target vector y.")

    return X, y


def build_pipeline() -> Pipeline:
    """
    Constructs an end-to-end sklearn Pipeline with ColumnTransformer preprocessing
    and LinearRegression estimator.
    """
    preprocessor = ColumnTransformer(
        transformers=[
            (
                "num",
                StandardScaler(),
                NUMERIC_FEATURES,
            ),
            (
                "cat",
                OneHotEncoder(handle_unknown="ignore", sparse_output=False),
                CATEGORICAL_FEATURES,
            ),
        ]
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("regressor", LinearRegression()),
        ]
    )
    return pipeline


def train_and_evaluate(
    csv_path: str = DATA_PATH,
    test_size: float = 0.20,
    random_state: int = 42,
    save_artifacts: bool = True,
) -> Dict[str, Any]:
    """
    Executes reproducible train/test split, model fitting, test evaluation,
    and artifact serialization.
    """
    print("=" * 65)
    print("BASELINE EV ENERGY REGRESSION MODEL TRAINING & EVALUATION")
    print("=" * 65)
    print("IMPORTANT DISCLOSURE: Trained on synthetic Virtual EV simulation data.")
    print("Results measure model fit on simulated distribution; not physical EV tests.\n")

    # 1. Load and validate
    X, y = load_and_validate_data(csv_path)
    total_samples = len(X)
    print(f"[1/5] Loaded dataset: {total_samples} samples across {len(X.columns)} features.")
    print(f"      - Numeric features ({len(NUMERIC_FEATURES)}): {NUMERIC_FEATURES}")
    print(f"      - Categorical features ({len(CATEGORICAL_FEATURES)}): {CATEGORICAL_FEATURES}")
    print(f"      - Target: '{TARGET_COL}'")

    # 2. Train / Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )
    print(f"\n[2/5] Performed reproducible train/test split (seed={random_state}):")
    print(f"      - Training samples: {len(X_train)} ({(1 - test_size) * 100:.0f}%)")
    print(f"      - Held-out test samples: {len(X_test)} ({test_size * 100:.0f}%)")

    # 3. Build & Train Pipeline
    print("\n[3/5] Fitting ColumnTransformer + LinearRegression Pipeline...")
    pipeline = build_pipeline()
    pipeline.fit(X_train, y_train)

    # Inspect feature space dimensionality after One-Hot Encoding
    preprocessor = pipeline.named_steps["preprocessor"]
    cat_encoder = preprocessor.named_transformers_["cat"]
    cat_feature_names = list(cat_encoder.get_feature_names_out(CATEGORICAL_FEATURES))
    encoded_feature_names = NUMERIC_FEATURES + cat_feature_names
    num_encoded_features = len(encoded_feature_names)
    print(f"      - Transformed feature dimensionality: {num_encoded_features} columns")

    # 4. Evaluate on Held-Out Test Set
    print("\n[4/5] Evaluating on held-out test set...")
    y_pred = pipeline.predict(X_test)

    mae = float(mean_absolute_error(y_test, y_pred))
    mse = float(mean_squared_error(y_test, y_pred))
    rmse = float(np.sqrt(mse))
    r2 = float(r2_score(y_test, y_pred))

    print("-" * 65)
    print("MODEL EVALUATION METRICS (TEST SET):")
    print(f"  MAE  (Mean Absolute Error):      {mae:.4f} kWh")
    print(f"  RMSE (Root Mean Squared Error):  {rmse:.4f} kWh")
    print(f"  R²   (Coefficient of Deter.):    {r2:.4f}")
    print("-" * 65)

    # Actual vs Predicted Sample Comparison Table
    sample_size = 8
    sample_df = pd.DataFrame(
        {
            "Distance (km)": X_test["distance_km"].iloc[:sample_size].values,
            "Speed (km/h)": X_test["average_speed_kmph"].iloc[:sample_size].values,
            "Style": X_test["driving_style"].iloc[:sample_size].values,
            "Actual (kWh)": y_test.iloc[:sample_size].values,
            "Predicted (kWh)": np.round(y_pred[:sample_size], 3),
        }
    )
    sample_df["Error (kWh)"] = np.round(sample_df["Predicted (kWh)"] - sample_df["Actual (kWh)"], 3)
    print("\nSample Test Predictions vs Actuals:")
    print(sample_df.to_string(index=False))

    # 5. Save Artifacts
    results_summary = {
        "model_name": "LinearRegression",
        "target": TARGET_COL,
        "metrics": {
            "mae": round(mae, 4),
            "rmse": round(rmse, 4),
            "r2": round(r2, 4),
        },
        "dataset_split": {
            "total_samples": total_samples,
            "train_samples": len(X_train),
            "test_samples": len(X_test),
            "test_size": test_size,
            "random_state": random_state,
        },
        "features": {
            "numeric_features": NUMERIC_FEATURES,
            "categorical_features": CATEGORICAL_FEATURES,
            "encoded_feature_count": num_encoded_features,
            "encoded_feature_names": encoded_feature_names,
        },
        "synthetic_data_disclosure": (
            "Model trained and evaluated on synthetic Virtual EV trip data. "
            "Metrics reflect performance on simulated distribution and do not "
            "represent validated real-world physical EV measurements."
        ),
    }

    if save_artifacts:
        os.makedirs(ARTIFACTS_DIR, exist_ok=True)
        joblib.dump(pipeline, MODEL_PATH)
        with open(FEATURES_PATH, "w") as f:
            json.dump(results_summary, f, indent=2)

        print(f"\n[5/5] Saved Artifacts:")
        print(f"      - Trained Pipeline: {MODEL_PATH}")
        print(f"      - Metadata/Schema:  {FEATURES_PATH}")

    print("=" * 65)
    print("[SUCCESS] Baseline Regression Model trained and evaluated successfully.")
    print("=" * 65)

    return results_summary


def load_model(model_path: str = MODEL_PATH) -> Pipeline:
    """Loads the trained regression pipeline artifact for inference."""
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model artifact not found at {model_path}. Run training first.")
    return joblib.load(model_path)


def predict_energy(features_df: pd.DataFrame, model_path: str = MODEL_PATH) -> np.ndarray:
    """Predicts energy consumption in kWh for given raw input features DataFrame."""
    pipeline = load_model(model_path)
    return pipeline.predict(features_df)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Baseline EV Energy Regression Model")
    parser.add_argument("--test-size", type=float, default=0.20, help="Test set fraction (default: 0.20)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility (default: 42)")
    parser.add_argument("--data", type=str, default=DATA_PATH, help="Path to input features CSV")
    args = parser.parse_args()

    train_and_evaluate(
        csv_path=args.data,
        test_size=args.test_size,
        random_state=args.seed,
        save_artifacts=True,
    )
