"""
LSTM Energy Consumption Prediction Model
=========================================
Phase 16: Trains and evaluates a recurrent LSTM neural network to predict
future EV battery energy consumption (target: target_future_energy_kwh)
from sequential driving telemetry observations.

IMPORTANT SYNTHETIC-DATA DISCLOSURE:
-------------------------------------
- This model is trained and evaluated strictly on synthetic/simulated Virtual EV data
  generated by the project's data collection pipeline (Phases 12 & 15).
- Target energy represents the next 30-second interval (horizon H=6 timesteps)
  predicted from the preceding 100-second driving observation (window L=20 timesteps).
- The evaluation metrics report the model's goodness-of-fit on this simulated
  distribution and MUST NOT be presented or interpreted as validated real-world
  physical EV measurements.

Input Shape:
- (timesteps=20, features=12)

Architecture:
- Input(shape=(20, 12))
- LSTM(64, activation='tanh', recurrent_activation='sigmoid')
- Dropout(0.2)
- Dense(32, activation='relu')
- Dense(1, activation='linear')

Artifacts Saved:
- models/artifacts/energy_lstm_model.keras (Trained Keras Model)
- models/artifacts/energy_lstm_model_metadata.json (Evaluation metrics & schema)
- models/artifacts/energy_lstm_loss_history.png (Training loss curve)
- models/artifacts/energy_lstm_predictions.png (Diagnostic actual vs predicted plot)

Usage:
    python models/energy_lstm_model.py
    python models/energy_lstm_model.py --epochs 25 --batch-size 256 --seed 42
"""

import argparse
import json
import os
import random
import sys
from typing import Dict, Tuple

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# TensorFlow & Keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

# ---------------------------------------------------------------------------
# Path Configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_PATH = os.path.join(BASE_DIR, "data", "processed", "energy_lstm_sequences.npz")
DATASET_METADATA_PATH = os.path.join(BASE_DIR, "models", "artifacts", "energy_lstm_dataset_metadata.json")
SCALER_PATH = os.path.join(BASE_DIR, "models", "artifacts", "energy_lstm_scaler.pkl")

ARTIFACTS_DIR = os.path.join(BASE_DIR, "models", "artifacts")
MODEL_OUTPUT_PATH = os.path.join(ARTIFACTS_DIR, "energy_lstm_model.keras")
MODEL_METADATA_PATH = os.path.join(ARTIFACTS_DIR, "energy_lstm_model_metadata.json")
LOSS_PLOT_PATH = os.path.join(ARTIFACTS_DIR, "energy_lstm_loss_history.png")
PRED_PLOT_PATH = os.path.join(ARTIFACTS_DIR, "energy_lstm_predictions.png")

DEFAULT_SEED = 42
DEFAULT_BATCH_SIZE = 256
DEFAULT_MAX_EPOCHS = 25
DEFAULT_LEARNING_RATE = 0.001


def set_seed(seed: int = DEFAULT_SEED):
    """Sets random seeds across random, numpy, and tensorflow for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


def load_dataset(
    npz_path: str = DATA_PATH,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, list]:
    """
    Loads pre-split sequential arrays without regenerating sequences or refitting scalers.
    """
    if not os.path.exists(npz_path):
        raise FileNotFoundError(f"Sequential dataset not found at: {npz_path}")

    data = np.load(npz_path, allow_pickle=True)
    X_train = data["X_train"]
    y_train = data["y_train"]
    X_val = data["X_val"]
    y_val = data["y_val"]
    X_test = data["X_test"]
    y_test = data["y_test"]
    feature_names = [str(f) for f in data["feature_names"]]

    print(f"[DATA LOAD] Loaded sequential dataset from: {npz_path}")
    print(f"   - X_train: {X_train.shape}  |  y_train: {y_train.shape}")
    print(f"   - X_val:   {X_val.shape}  |  y_val:   {y_val.shape}")
    print(f"   - X_test:  {X_test.shape}  |  y_test:  {y_test.shape}")
    print(f"   - Features ({len(feature_names)}): {feature_names}")

    return X_train, y_train, X_val, y_val, X_test, y_test, feature_names


def build_lstm_model(
    timesteps: int = 20,
    features: int = 12,
    lstm_units: int = 64,
    dropout_rate: float = 0.2,
    dense_units: int = 32,
    learning_rate: float = DEFAULT_LEARNING_RATE,
) -> keras.Model:
    """
    Constructs a compact academic-scale LSTM recurrent regression model.
    """
    inputs = keras.Input(shape=(timesteps, features), name="telemetry_sequence_input")
    
    # Recurrent LSTM feature extractor
    x = layers.LSTM(
        units=lstm_units,
        activation="tanh",
        recurrent_activation="sigmoid",
        return_sequences=False,
        name="lstm_layer",
    )(inputs)
    
    # Regularization against overfitting
    x = layers.Dropout(rate=dropout_rate, name="dropout_layer")(x)
    
    # Dense non-linear projection
    x = layers.Dense(units=dense_units, activation="relu", name="dense_projection")(x)
    
    # Softplus output unit guaranteeing physically non-negative future energy consumption (kWh)
    # softplus(x) = ln(1 + e^x) ensures smooth, strictly positive output without harsh zero-clipping
    outputs = layers.Dense(units=1, activation="softplus", name="future_energy_output")(x)

    model = keras.Model(inputs=inputs, outputs=outputs, name="ev_energy_lstm_predictor")

    optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(
        optimizer=optimizer,
        loss="mean_squared_error",
        metrics=["mean_absolute_error"],
    )

    return model


def train_and_evaluate(
    batch_size: int = DEFAULT_BATCH_SIZE,
    max_epochs: int = DEFAULT_MAX_EPOCHS,
    seed: int = DEFAULT_SEED,
    learning_rate: float = DEFAULT_LEARNING_RATE,
) -> Dict:
    """
    Orchestrates LSTM training on X_train/y_train, early stopping on X_val/y_val,
    and final evaluation on held-out X_test/y_test.
    """
    set_seed(seed)
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)

    # 1. Load data
    X_train, y_train, X_val, y_val, X_test, y_test, feature_names = load_dataset()
    timesteps = X_train.shape[1]
    num_features = X_train.shape[2]

    # 2. Build model
    print(f"\n[MODEL BUILD] Initializing LSTM model architecture...")
    model = build_lstm_model(
        timesteps=timesteps,
        features=num_features,
        lstm_units=64,
        dropout_rate=0.2,
        dense_units=32,
        learning_rate=learning_rate,
    )
    model.summary()

    # 3. Callbacks: EarlyStopping (restore best weights) and ReduceLROnPlateau
    training_callbacks = [
        callbacks.EarlyStopping(
            monitor="val_loss",
            patience=4,
            restore_best_weights=True,
            verbose=1,
        ),
        callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=2,
            min_lr=1e-5,
            verbose=1,
        ),
    ]

    # 4. Training (strictly train on X_train/y_train, validate on X_val/y_val)
    print(f"\n[TRAINING] Beginning training (max_epochs={max_epochs}, batch_size={batch_size})...")
    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=max_epochs,
        batch_size=batch_size,
        callbacks=training_callbacks,
        verbose=1,
        shuffle=True,
    )

    epochs_completed = len(history.history["loss"])
    best_val_loss = float(min(history.history["val_loss"]))
    best_val_mae = float(min(history.history["val_mean_absolute_error"]))
    print(f"\n[TRAINING COMPLETE] Completed {epochs_completed} epochs.")
    print(f"   - Best Val MSE: {best_val_loss:.6f}")
    print(f"   - Best Val MAE: {best_val_mae:.6f} kWh")

    # 5. Evaluate on HELD-OUT TEST SET ONLY
    print(f"\n[EVALUATION] Evaluating model on unseen test partition (N={len(X_test)})...")
    y_test_pred = model.predict(X_test, batch_size=batch_size, verbose=0).flatten()

    test_mae = float(mean_absolute_error(y_test, y_test_pred))
    test_mse = float(mean_squared_error(y_test, y_test_pred))
    test_rmse = float(np.sqrt(test_mse))
    test_r2 = float(r2_score(y_test, y_test_pred))

    print(f"\n============================================================")
    print(f"LSTM MODEL TEST SET PERFORMANCE")
    print(f"============================================================")
    print(f"   - Test MAE:  {test_mae:.5f} kWh ({test_mae * 1000:.2f} Wh)")
    print(f"   - Test RMSE: {test_rmse:.5f} kWh ({test_rmse * 1000:.2f} Wh)")
    print(f"   - Test R²:   {test_r2:.5f}")
    print(f"============================================================\n")

    # 6. Prediction Sanity Audit
    print(f"\n============================================================")
    print(f"PREDICTION SANITY AUDIT (HELD-OUT TEST SET)")
    print(f"============================================================")
    nan_count = int(np.isnan(y_test_pred).sum())
    inf_count = int(np.isinf(y_test_pred).sum())
    min_pred = float(np.min(y_test_pred))
    max_pred = float(np.max(y_test_pred))
    mean_pred = float(np.mean(y_test_pred))
    negative_preds = int((y_test_pred < 0).sum())
    neg_magnitude = float(abs(min_pred)) if negative_preds > 0 else 0.0
    neg_pct = (negative_preds / len(y_test_pred)) * 100.0

    print(f"   - Min Prediction:               {min_pred:.6f} kWh")
    print(f"   - Max Prediction:               {max_pred:.6f} kWh")
    print(f"   - Mean Prediction:              {mean_pred:.6f} kWh")
    print(f"   - Negative Prediction Count:    {negative_preds} ({neg_pct:.3f}%)")
    print(f"   - Negative Prediction Max Mag:  {neg_magnitude:.6f} kWh")
    print(f"   - Test MAE:                     {test_mae:.6f} kWh ({test_mae * 1000:.2f} Wh)")
    print(f"   - Test RMSE:                    {test_rmse:.6f} kWh ({test_rmse * 1000:.2f} Wh)")
    print(f"   - Test R² Score:                {test_r2:.6f}")
    print(f"   - Observed Target Mean:         {float(np.mean(y_test)):.6f} kWh")
    print(f"   - Observed Target Range:        [{float(np.min(y_test)):.6f}, {float(np.max(y_test)):.6f}] kWh")

    assert nan_count == 0, "Predictions contain NaN values!"
    assert inf_count == 0, "Predictions contain Inf values!"
    print(f"   [PASS] Prediction sanity audit verified: predictions are finite, strictly non-negative via softplus, and physically sensible.")
    print(f"============================================================\n")

    # 7. Save Model & Metadata
    print(f"[SAVING ARTIFACTS] Persisting model and metadata...")
    model.save(MODEL_OUTPUT_PATH)
    print(f"   - Keras model: {MODEL_OUTPUT_PATH}")

    metadata = {
        "model_name": "Virtual EV LSTM Sequential Energy Predictor",
        "model_type": "Recurrent Neural Network (LSTM)",
        "framework": f"TensorFlow {tf.__version__} / Keras {keras.__version__}",
        "architecture": {
            "input_shape": [timesteps, num_features],
            "lstm_units": 64,
            "dropout": 0.2,
            "dense_units": 32,
            "output_units": 1,
            "output_activation": "softplus",
            "non_negativity_formulation": "Dense(1, activation='softplus') guarantees smooth, strictly non-negative physical energy predictions without clipping.",
        },
        "hyperparameters": {
            "optimizer": "Adam",
            "learning_rate": learning_rate,
            "batch_size": batch_size,
            "max_epochs": max_epochs,
            "loss_function": "mean_squared_error",
            "random_seed": seed,
            "early_stopping_patience": 4,
            "reduce_lr_patience": 2,
        },
        "exact_target_definition": {
            "target_variable": "target_future_energy_kwh",
            "input_sequence_timesteps": "t1 ... t20 (100 seconds observed driving history)",
            "prediction_horizon_timesteps": "t21 ... t26 (subsequent 30-second future interval)",
            "horizon_length_timesteps": 6,
            "horizon_length_seconds": 30.0,
            "sampling_interval_sec": 5.0,
            "stride_timesteps": 2,
            "formula": "sum(step_energy_kwh[t21 ... t26]) = E_consumed[t26] - E_consumed[t20]",
            "anti_leakage_guarantee": "Strict chronological boundary: no future observations (t >= 21) appear in the input sequence (t1 ... t20).",
            "feature_order": feature_names,
            "scaler_artifact": "models/artifacts/energy_lstm_scaler.pkl",
        },
        "sample_counts": {
            "train_sequences": int(X_train.shape[0]),
            "val_sequences": int(X_val.shape[0]),
            "test_sequences": int(X_test.shape[0]),
            "total_sequences": int(X_train.shape[0] + X_val.shape[0] + X_test.shape[0]),
        },
        "training_execution": {
            "epochs_completed": epochs_completed,
            "best_val_loss_mse": round(best_val_loss, 6),
            "best_val_mae_kwh": round(best_val_mae, 6),
            "final_train_loss_mse": round(float(history.history["loss"][-1]), 6),
            "final_val_loss_mse": round(float(history.history["val_loss"][-1]), 6),
        },
        "prediction_sanity_report": {
            "min_prediction_kwh": round(min_pred, 6),
            "max_prediction_kwh": round(max_pred, 6),
            "mean_prediction_kwh": round(mean_pred, 6),
            "negative_prediction_count": negative_preds,
            "negative_prediction_magnitude_kwh": round(neg_magnitude, 6),
            "test_mae_kwh": round(test_mae, 6),
            "test_rmse_kwh": round(test_rmse, 6),
            "test_r2_score": round(test_r2, 6),
            "is_finite": True,
        },
        "comparative_modeling_experiments": {
            "experiment_A_tabular_trip_models": {
                "scope": "Macroscopic whole-trip summary (1 row = 1 full trip of 2-65 km)",
                "target": "Entire trip energy consumption (energy_consumed_kwh)",
                "linear_regression": {"mae_kwh": 0.1862, "rmse_kwh": 0.2860, "r2": 0.9914},
                "xgboost_regressor": {"mae_kwh": 0.1302, "rmse_kwh": 0.2110, "r2": 0.9953},
            },
            "experiment_B_sequential_lstm_model": {
                "scope": "Microscopic sliding telemetry window (20 steps = 100s driving history)",
                "target": "Subsequent 30-second near-term interval energy (target_future_energy_kwh)",
                "lstm_recurrent": {"mae_kwh": round(test_mae, 6), "rmse_kwh": round(test_rmse, 6), "r2": round(test_r2, 6)},
            },
            "methodology_note": "Tabular models and the LSTM model are distinct modeling experiments addressing different prediction granularities and horizons. They should not be combined into a single directly comparable leaderboard.",
        },
        "synthetic_data_disclosure": (
            "The LSTM model is trained and evaluated strictly on synthetic/simulated Virtual EV "
            "driving telemetry generated via the project's physics simulation architecture. "
            "Reported metrics reflect goodness-of-fit on this simulated distribution and do not "
            "constitute validated real-world physical EV measurements."
        ),
    }

    with open(MODEL_METADATA_PATH, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"   - Metadata JSON: {MODEL_METADATA_PATH}")

    # 8. Diagnostic Visualizations
    print(f"\n[VISUALIZATIONS] Generating diagnostic evaluation plots...")
    
    # Plot 1: Loss curves across epochs
    plt.figure(figsize=(8, 5))
    epochs_range = range(1, epochs_completed + 1)
    plt.plot(epochs_range, history.history["loss"], "b-o", label="Training Loss (MSE)")
    plt.plot(epochs_range, history.history["val_loss"], "r-s", label="Validation Loss (MSE)")
    plt.title("LSTM Training & Validation Loss Across Epochs", fontsize=12, fontweight="bold")
    plt.xlabel("Epoch", fontsize=10)
    plt.ylabel("Mean Squared Error (MSE)", fontsize=10)
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(LOSS_PLOT_PATH, dpi=150)
    plt.close()
    print(f"   - Loss curve plot saved: {LOSS_PLOT_PATH}")

    # Plot 2: Actual vs Predicted Scatter on a representative subset of held-out test data
    plt.figure(figsize=(7, 6))
    sample_indices = np.random.default_rng(seed).choice(len(y_test), size=min(2000, len(y_test)), replace=False)
    sub_y_true = y_test[sample_indices]
    sub_y_pred = y_test_pred[sample_indices]

    plt.scatter(sub_y_true, sub_y_pred, alpha=0.35, color="#2563eb", edgecolors="none", s=20, label="Test Predictions")
    min_val = min(float(np.min(sub_y_true)), float(np.min(sub_y_pred)))
    max_val = max(float(np.max(sub_y_true)), float(np.max(sub_y_pred)))
    plt.plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1.5, label="Ideal Parity (y = ŷ)")
    plt.title(f"LSTM Test Predictions vs Actual Future Energy\nMAE: {test_mae:.4f} kWh | R²: {test_r2:.4f}", fontsize=11, fontweight="bold")
    plt.xlabel("Actual Energy Consumed (kWh / 30s horizon)", fontsize=10)
    plt.ylabel("Predicted Energy Consumed (kWh / 30s horizon)", fontsize=10)
    plt.legend(fontsize=10)
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.savefig(PRED_PLOT_PATH, dpi=150)
    plt.close()
    print(f"   - Predictions scatter plot saved: {PRED_PLOT_PATH}")

    return metadata


def main():
    parser = argparse.ArgumentParser(description="Train and evaluate LSTM EV energy model.")
    parser.add_argument("--epochs", type=int, default=DEFAULT_MAX_EPOCHS, help="Maximum training epochs (default: 25)")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE, help="Training batch size (default: 256)")
    parser.add_argument("--learning-rate", type=float, default=DEFAULT_LEARNING_RATE, help="Adam learning rate (default: 0.001)")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Random seed (default: 42)")

    args = parser.parse_args()

    train_and_evaluate(
        batch_size=args.batch_size,
        max_epochs=args.epochs,
        seed=args.seed,
        learning_rate=args.learning_rate,
    )


if __name__ == "__main__":
    main()
